module : cnn.feature_extraction_single.FeatureExtraction
model : cnn.vit_base_patch16_224
data_root : C:/Users/shinp/Desktop/work/data/surg_extract #/mnt/polyaxon/data1
dataset : cholec80_feature_extract_single.Cholec80FeatureExtract
out_features : 5
task_features : 25
input_height : 224
input_width : 224
# batch_size : 1000
batch_size : 128
fps_sampling : 1
fps_sampling_test : 1
learning_rate : 0.0005
dataset_mode : img_multilabel
early_stopping_metric : val_f1
pretrained : True
save_top_k : 1
# max_epochs : 15 # 30
# min_epochs : 6 # 20
# max_epochs : 30
# min_epochs : 20
max_epochs : 30
min_epochs : 20
num_tasks : 2
num_sanity_val_steps : 4
test_extract : True
#accelerator: ddp_spawn
num_workers : 3
gpus : 1 # all available -1
fold : 0
exp_name : 'exp'
task: 'step'


#resume_from_checkpoint : logs/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model/checkpoints/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model-epoch=10-val_acc_phase=0.83.ckpt

