module : mstcn.tecno_single.TeCNO
model : mstcn.MultiStageModel_single
dataset : cholec80_single_teacher.Cholec80
out_features : 8
task_features : 8
num_workers : 3
batch_size : 1
features_per_seconds : 1
features_subsampling : 1
log_every_n_steps : 1
mstcn_causal_conv : True
# learning_rate : 0.00007
learning_rate : 0.0005
max_epochs : 30
min_epochs : 20

mstcn_layers : 8
mstcn_f_maps : 32
mstcn_f_dim: 768
mstcn_stages : 2
early_stopping_metric : val_S1_f1 #val_S2_f1
save_top_k : 1
gpus : ['1']
data_root : C:/Users/shinp/Desktop/work/surg_vu/logs

num_sanity_val_steps: 0
fold : 0
exp_name : 'exp'
# C:/Users/shinp/Desktop/work/TeCNO/logs/240705-083222_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model/cholec80_pickle_export/1.0fps/video_1_1.0fps.pkl
